project:
  type: website
  output-dir: docs
website:  
  title: "2小时入门R语言"
  navbar:
    logo-alt: "顶刊研习社"              
    logo-href: index.qmd          
    background: primary
    left:
      - href: index.qmd
        text: Home
      - m1.qmd
      - m2.qmd
      - m3.qmd
      - m4.qmd
      - m5.qmd
    tools:
      - icon: envelope
        href: lizongzhang9@qq.com
  page-footer:
    right: "Logic in Mind, R in Hand"
    left: "&copy; Copyright 2026, 顶刊研习社"
format:
  html:
    theme: spacelab    
    fontcolor: "#044875"
    css: style.css
    toc: true
editor: source
execute:
  default-language: R


